#!/usr/bin/env python

from zensols import deepnlp

# initialize the NLP system
deepnlp.init()

if 0:
    import zensols.deepnlp.transformer as tran
    tran.turn_off_huggingface_downloads()


if (__name__ == '__main__'):
    from zensols.cli import ConfigurationImporterCliHarness
    harness = ConfigurationImporterCliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.calsum.ApplicationFactory',
        proto_args={
            0: 'proto',
            1: 'batch',
            2: 'debug',
            3: 'generate',
        }[0],
        proto_factory_kwargs={
            'reload_pattern': r'^zensols.calsum\.(?!domain)'},
    )
    harness.run()
